### PR TITLE
Update table styles

### LINKED ISSUE #170: Create the Table component
**Description**
With the `Table` component having been built in Vocabulary with the markup and styling already defined, it's time to get the Vue version of the component.

The Table component is a layout and as such has a lot of markup involved for even the very simple usecases. Having a Vue component with `slot`s takes a huge load off the developer to focus on the main content.

References:
- creativecommons/vocabulary#143
- [Table @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=904%3A0)

### PR DESCRIPTION
**Pull request by Dhruvi16**
**Fixes**

Fixes #170 by @panchovm 

**Description**

**Type of PR** 

This PR is a [feature|hotfix|refactor].

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ ] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
@Dhruvi16 while you can (and should) continue to work on this, merging is blocked till #203 is merged.

**Comment by dhruvkb** [comment]
Blockers have been cleared, @Dhruvi16 please continue.

**Comment by Dhruvi16** [comment]
I have added the table and table cell stories and I guess the classes are not exported well. I have completely removed` table.vue` component as I thought we do not need it anymore. Please check this out and lemme know what you think.

**Comment by zackkrida** [comment]
@Dhruvi16 thanks for your work on this, but I'm going to write up some clearer instructions for a table component and how we would like the props to be structured. I'm going to close this but I'll let you know when that clarified version is ready for review!

**Pull request closed without merging**
