### PR TITLE
Expand icon prop

### LINKED ISSUE #2: Expand icon prop
Currently the `icon`, `iconList` and `iconSet` props in many components accept just a `String` that is automatically mapped to the `fas` subset of FontAwesome icons. 

Any deviation from this icon set must be achieved by populating the respective add-on slot housing the icon. This can get cumbersome and unnecessarily verbose.

A viable alternative would be to allow passing each icon either as a `String` (that is programmatically mapped to `['fas', icon]`) or as an array listing the subset and the icon name. 

This approach would also simplify template declarations of `FontAwesomeIcon` components 
as this functionality is implemented in the `FontAwesomeIcon` Vue component itself).

```html
<FontAwesomeIcon :icon="icon"/>
```

### PR DESCRIPTION
**Pull request by sayima-n**
**Fixes**
Fixes #2

**Description**

Expose the `icon` prop of the `FontAwesomeIcon` component, through the various `icon`, and `iconSet` props.

**Type of PR** 
This PR is a feature.

**Tests**

- Provide string arrays (e.g: `['fas', 'hand-point-up']`) to the components exposing an `icon` prop
- Provide arrays of string arrays (e.g: `[['fas', 'hand-point-up'], ['fas', 'hand-point-down']]`) to the components exposing an `iconSet` prop.

You can also view the changes on the Button, InputField, ProgressBar, Rating, SelectField, Statistic, SwitchField, NavigationLink, and TrailCrumb pages of the Styleguide.

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by sayima-n** [comment]
@dhruvkb I updated the Styleguide to test and present the changes, but I can remove some or all of the edit if you think it bloats the documentation

**Comment by dhruvkb** [comment]
@sayima-n oh, don't worry. The more explicit and detailed the documentation, the better.

**Comment by sayima-n** [comment]
@dhruvkb great :smiley:
I think it's ready to be to be reviewed then

**Comment by dhruvkb** [comment]
_Since I couldn't find you on Slack:_

The date for submitting your final applications is near and we're still open to receiving your proposals. To make this simple, we have made a template that should help you get started. Please hurry up as the deadline is merely days away.

 https://docs.google.com/document/d/1qJF51MNk2KD_A0g3e3LRFmK-p5DD4owg7lXByjQWclM/edit

The template contains questions that are asked on the Outreachy application form as well as some concerns that CC has apart from those.

**Comment by sayima-n** [comment]
@dhruvkb thank you so much. I'm filling it now...

**Comment by sayima-n** [comment]
@dhruvkb hello I emailed you the form via the email on your website. Could you please let me know when you see it? or what is the best way to send it to you?
Also what else is needed for the pull request to be accepted?

**Comment by dhruvkb** [comment]
@sayima-n I have not received your email. You should ideally DM your proposal application to me and @hugosolar on Slack.

**Comment by sayima-n** [comment]
Sorry for the confusion I go by Sayima Nima. Could you please add me to the creativecommons slack with this email: sayima.nima@gmail.com?

**Pull request merged**
