### PR TITLE
Fixed storybook link in README and also removed styleguide

### LINKED ISSUE #174: Storybook link is not working in README.md
**Description**
Link to storybook in README.md gives a 404 error.

**Reproduction**
Click on the link in Demo section of README.md

**Expected behaviour**
Should redirect to CC-vocabulary storybook.

**Screenshots**

cc-vocabulary storybook error

**Additional context**
I am also updating the live styleguide as this has been deleted.

**Want to take up?**

Yes

### PR DESCRIPTION
**Pull request by techievivek**
**Fixes**

Fixes #174 by @techievivek

**Description**
It updates the storybook link in README and also removes the styleguide that has been deleted.

**Type of PR** 
This PR is a [feature|hotfix|refactor].

**Technicalities**
Just updates the link.

**Tests**
Click on the stylebook link.

**Screenshots**

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by Dhruvi16** [comment]
I think the issue persists. It still takes to Page not found. This is the link https://cc-vue-vocabulary.netlify.com/storybook it takes to.
image

**Comment by techievivek** [comment]
I will update it, sorry for the mistake.

**Comment by techievivek** [comment]
@dhruvkb is this the correct URL https://cc-vocabulary.netlify.com/

**Comment by techievivek** [comment]
@dhruvkb Because what I remember it had **storybook** part too in URL? But I am not getting that link anywhere.

**Comment by techievivek** [comment]
@dhruvkb Also please help me how can I update this edit, do I have to create a new **Issue** and then a new **PR**, or is there any way to directly get the change?

**Comment by dhruvkb** [comment]
Actually the link was `/storybook` but it was changed again! @techievivek please create a new PR for this issue.

**Pull request merged**
