### PR TITLE
Update GitHub corners

### LINKED ISSUE #118: Updates to GitHub Corners
**Description**

We want to:
1. Remove the Branded and Colored options.
2. Update Invertible to have two knobs: Black on white, or White on black.
3. Keep Corners (they can be left or right).
4. Remove Positions.

Related ticket: https://github.com/creativecommons/vocabulary/issues/52

### PR DESCRIPTION
**Pull request by jshreyans**
**Fixes**

Fixes #118 by @annatuma 

**Description**
Following changes have been implemented:
- [x] Remove the Branded and Colored options.
- [x] Update Invertible to have two knobs: Black on white, or White on black.
- [x] Remove Positions.

**Type of PR** 
This PR is a refactor.

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
@jshreyans you not only need to remove these stories but also these features from the component as well. So the `GitHubCorner` component would only have two colour variants and two directions.

**Comment by jshreyans** [comment]
@dhruvkb Ok got it. But I can't see the `GithubCorner` component in the Vocabulary repo.

**Comment by jshreyans** [comment]
@dhruvkb I've made changes to the component. Also, in order to remove positions, do I remove these configuration instructions too:
https://github.com/creativecommons/vue-vocabulary/blob/96fa34c3d18c5d339fab79556db2b1454e4ee0f0/src/elements/GitHubCorner/GitHubCorner.vue#L81-L85

**Comment by jshreyans** [comment]
I figured out we _do_ need to remove that configuration code. I've pushed some changes. Although, I do want to ask if we will be keeping the `shades` option now that we are working with only 2 colors.

**Comment by dhruvkb** [comment]
No we'll just use `Invertible` to switch the black to white.

**Pull request merged**
